sudo: false
language: node_js
node_js:
  - '8'
env:
  - EGG_SERVER_ENV=unittest
install:
  - npm i npminstall && npminstall
  - docker-compose up -d redis
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
