version: '3'
services:
  mysql:
    image: mysql:5
    environment:
      - MYSQL_USER=batch-sms
      - MYSQL_PASSWORD=batch-sms
      - MYSQL_DATABASE=batch-sms
      - MYSQL_ROOT_PASSWORD=mypass
    ports:
      - 3309:3306
  redis:
    image: redis
    ports:
      - 6381:6379
