version: '3'
services:
  mysql:
    image: mysql:5
    environment:
      - MYSQL_USER=egg-ts-awesome
      - MYSQL_PASSWORD=egg-ts-awesome
      - MYSQL_DATABASE=egg-ts-awesome
      - MYSQL_ROOT_PASSWORD=mypass
    ports:
      - 3309:3306
  redis:
    image: redis
    ports:
      - 6381:6379
